apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: simple-webapp-ingress
  namespace: default
spec:
  tls:
  - hosts:
      - simple-webapp.hasankaradmir.com
    secretName: simple-webapp-tls
  rules:
  - host: simple-webapp.hasankaradmir.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-webapp-service
            port:
              number: 80