apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
  labels:
    app: flask
spec:
  type: LoadBalancer
  ports:
  - port: 7999
    targetPort: 8000
    protocol: TCP
  selector:
    app: flask
