apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: flask
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30007
  selector:
    app: flask
